spring:
  application:
    name: batch-processor
  security:
    oauth2:
      resourceserver:
#        opaquetoken:
#          introspection-uri: ${keycloak-server}/realms/${keycloak-realm}/protocol/openid-connect/token/introspect
#          client-id: maybank-client
#          client-secret: Oinx6ZqwYh1BKsFkOu6DP22R188jY98Z
        jwt:
          jwk-set-uri: ${keycloak-server}/realms/${keycloak-realm}/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3366/batch_processor_db
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8089


keycloak-server: http://localhost:8080
keycloak-realm: maybank-realm

logging:
  level:
    org:
      springframework:
        security: DEBUG